---
title: "Employed Women"
description: |
  Analysis of employed workers by gender (both full-time and part-time)
author: Kandace Loualhati
        original data from TidyTuesday
date: September 17, 2024
format: html
execute: 
  warning: false
  message: false
---

```{r}
# load in packages
library(tidyverse)
library(readr)
library(dplyr)
# read in csv file
employed_gender <- read.csv("employed_gender.csv")
# plot line plots depicting the difference in full-time workers (by gender, by year)
ggplot(employed_gender) +
  geom_line(aes(x = year, y = full_time_female), color = "pink") +
  geom_line(aes(x = year, y = full_time_male), color = "lightblue") +
  labs(
    x = "Year",
    y = "% of Full-Time Workers",
    title = "Layered Line Plot of Male vs Female Full-Time Workers"
  )
```

```{r}
ggplot(employed_gender) +
  geom_line(aes(x = year, y = part_time_female), color = "pink") +
  geom_line(aes(x = year, y = part_time_male), color = "lightblue") +
  labs(
    x = "Year",
    y = "% of Part-Time Workers",
    title = "Layered Line Plot of Male vs Female Part-Time Workers"
  )
```

Code from: tidytuesday/data/2019/2019-03-05/employed_gender.csv at master · rfordatascience/tidytuesday (github.com)
